version: '3.8'

services:
  abdm-wrapper:
    build:
      context: .
      dockerfile: Dockerfile
    image: abdm-wrapper:latest
    ports:
      - '8082:8082'
    depends_on:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_HOST: mongodb
      SPRING_DATA_MONGODB_PORT: 27017
    networks:
      - docker_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  mongodb:
    image: mongodb/mongodb-community-server:latest
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongodb_vol:/data/db
    networks:
      - docker_network

volumes:
  mongodb_vol:

networks:
  docker_network:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1500